export const UserActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  TOGGLE_USER_SIGN_IN_HIDDEN: "TOGGLE_USER_SIGN_IN_HIDDEN",
  EMAIL_SIGN_IN_START: "EMAIL_SIGN_IN_START",
  EMAIL_SIGN_IN_SUCCESS: "EMAIL_SIGN_IN_SUCCESS",
  EMAIL_SIGN_IN_FAILURE: "EMAIL_SIGN_IN_FAILURE",
};
