import BreakfastIcon from "../../assets/svg/restaurant-icons/breakfast.svg";
import SoupIcon from "../../assets/svg/restaurant-icons/hot-soup.svg";
import PastaIcon from "../../assets/svg/restaurant-icons/pasta.svg";
import PizzaIcon from "../../assets/svg/restaurant-icons/pizza.svg";
import DessertIcon from "../../assets/svg/restaurant-icons/cake.svg";
import SideDishIcon from "../../assets/svg/restaurant-icons/french-fries.svg";
import GrillIcon from "../../assets/svg/restaurant-icons/beef.svg";
import SaladIcon from "../../assets/svg/restaurant-icons/salad.svg";
import DishIcon from "../../assets/svg/restaurant-icons/dish.svg";

const RESTAURANT_DATA = [
  {
    categoryID: 1,
    categoryName: "Mic Dejun / Breakfast",
    categoryIcon: BreakfastIcon,
    products: [
      {
        productID: 11,
        nameRO: "English Breakfast",
        nameENG: "",
        alergens: "[1, 11, 14]",
        quantity: "450 gr",
        price: 29,
        descriptionRO:
          "Fasole rosie, cabanos, bacon, oua ochi, ciuperci, rosie",
        descriptionENG:
          "Red beans, dry sausage, bacon, fried eggs, mushrooms, tomato",
      },
      {
        productID: 12,
        nameRO: "Omelta",
        nameENG: "Omlette",
        alergens: "[1]",
        quantity: "150 gr",
        price: 18,
        descriptionRO: "3 oua",
        descriptionENG: "3 eggs",
      },
      {
        productID: 13,
        nameRO: "Omelta Romaneasca",
        nameENG: "Romanian Omlette",
        alergens: "[1, 2]",
        quantity: "300 gr",
        price: 23,
        descriptionRO: "3 oua, bacon, cascaval",
        descriptionENG: "3 eggs, bacon, cheese",
      },
      {
        productID: 14,
        nameRO: "Oua Fierte",
        nameENG: "Boiled Eggs",
        alergens: "[1]",
        quantity: "50 gr",
        price: 3,
        descriptionRO: "",
        descriptionENG: "",
      },
      {
        productID: 15,
        nameRO: "Crenvursti",
        alergens: "[14]",
        nameENG: "Sausages",
        quantity: "150 gr",
        price: 8,
        descriptionRO: "",
        descriptionENG: "",
      },
    ],
  },
  {
    categoryID: 2,
    categoryName: "Extra",
    products: [
      {
        productID: 15,
        nameRO: "Cascaval",
        nameENG: "Cheese",
        alergens: "[2]",
        quantity: "50 gr",
        price: 4,
        descriptionRO: "",
        descriptionENG: "",
      },
      {
        productID: 16,
        nameRO: "Telemea",
        nameENG: "",
        alergens: "[2]",
        quantity: "50 gr",
        price: 4,
        descriptionRO: "",
        descriptionENG: "",
      },
      {
        productID: 17,
        nameRO: "Mozzarella",
        nameENG: "",
        alergens: "[2]",
        quantity: "50 gr",
        price: 5,
        descriptionRO: "",
        descriptionENG: "",
      },
      {
        productID: 18,
        nameRO: "Muschi File",
        nameENG: "",
        quantity: "50 gr",
        price: 5,
        descriptionRO: "",
        descriptionENG: "",
      },
      {
        productID: 19,
        nameRO: "Salam",
        nameENG: "Salami",
        quantity: "50 gr",
        price: 4,
        descriptionRO: "",
        descriptionENG: "",
      },
      {
        productID: 20,
        nameRO: "Sunca presata",
        nameENG: "Ham",
        quantity: "50 gr",
        price: 4,
        descriptionRO: "",
        descriptionENG: "",
      },
      {
        productID: 21,
        nameRO: "Rosii",
        nameENG: "Tomates",
        quantity: "150 gr",
        price: 6,
        descriptionRO: "",
        descriptionENG: "",
      },
      {
        productID: 22,
        nameRO: "Castraveti",
        nameENG: "Cucumbers",
        quantity: "150 gr",
        price: 7,
        descriptionRO: "",
        descriptionENG: "",
      },

      {
        productID: 23,
        nameRO: "Supliment",
        nameENG: "Supplement",
        quantity: "50 gr",
        price: 3,
        descriptionRO: "Gem, miere, unt [2], mustar [12, 14], ketchup [14]",
        descriptionENG: "Jam, honey, butter, mustard, ketchup",
      },
    ],
  },
  {
    categoryID: 3,
    categoryName: "Supe - Ciorbe / Soups",
    categoryIcon: SoupIcon,
    products: [
      {
        productID: 24,
        nameRO: "Ciorba de Vacuta",
        nameENG: "Beef Soup",
        alergens: "[11]",
        quantity: "400 gr",
        price: 15,
        descriptionRO: "",
        descriptionENG: "",
      },
      {
        productID: 25,
        nameRO: "Ciorba Ardeleneasca",
        nameENG: "Transylvanian Soup",
        alergens: "[11, 14]",
        quantity: "400 gr",
        price: 15,
        descriptionRO: "",
        descriptionENG: "",
      },
      {
        productID: 26,
        nameRO: "Supa Zilei",
        nameENG: "Soup of the Day",
        quantity: "400 gr",
        price: 15,
        descriptionRO: "",
        descriptionENG: "",
      },
      {
        productID: 27,
        nameRO: "Ardei Iute",
        nameENG: "Chilli Pepper",
        quantity: "1 buc / 1 pcs",
        price: 3,
        descriptionRO: "",
        descriptionENG: "",
      },
      {
        productID: 28,
        nameRO: "Smantana",
        nameENG: "Sour Cream",
        alergens: "[2]",
        quantity: "50 gr",
        price: 3,
        descriptionRO: "",
        descriptionENG: "",
      },
      {
        productID: 29,
        nameRO: "Paine",
        nameENG: "Bread",
        quantity: "120 gr",
        price: 3,
        descriptionRO: "",
        descriptionENG: "",
      },
    ],
  },
  {
    categoryID: 4,
    categoryName: "Fel de Baza / Main Course",
    categoryIcon: DishIcon,
    products: [
      {
        productID: 30,
        nameRO: "Snitzel de Pui cu cartofi Prajiti / Bread",
        nameENG: "Chicken snitzel with french fries",
        alergens: "[1, 9, 12]",
        quantity: "450 gr",
        price: 35,
        descriptionRO: "",
        descriptionENG: "",
      },
      {
        productID: 31,
        nameRO: "Ciolan de porc cu iahnie de fasole",
        nameENG: "Pork steak with bean stew",
        alergens: "[11]",
        quantity: "750 gr",
        price: 57,
        descriptionRO: "",
        descriptionENG: "",
      },
      {
        productID: 32,
        nameRO: "Costita de porc cu afumatura de fasole",
        nameENG: "Smoked pork ribs with sauerkraut",
        alergens: "[11]",
        quantity: "600 gr",
        price: 48,
        descriptionRO: "",
        descriptionENG: "",
      },
      {
        productID: 33,
        nameRO: "Gulas",
        nameENG: "Goulash",
        alergens: "[11]",
        quantity: "600 gr",
        price: 39,
        descriptionRO: "",
        descriptionENG: "",
      },
    ],
  },
  {
    categoryID: 5,
    categoryName: "Gratar / Grill",
    categoryIcon: GrillIcon,
    products: [
      {
        productID: 34,
        nameRO: "Muschi de vita",
        nameENG: "Sirloin steak",
        quantity: "230 gr",
        price: 68,
        descriptionRO: "",
        descriptionENG: "",
      },
      {
        productID: 35,
        nameRO: "Antricot",
        nameENG: "entrecote",
        quantity: "250 gr",
        price: 48,
        descriptionRO: "",
        descriptionENG: "",
      },
      {
        productID: 36,
        nameRO: "vrabioara",
        nameENG: "sirloin",
        quantity: "300 gr",
        price: 52,
        descriptionRO: "",
        descriptionENG: "",
      },
      {
        productID: 37,
        nameRO: "Piept de pui",
        nameENG: "Chicken breast",
        quantity: "220 gr",
        price: 27,
        descriptionRO: "",
        descriptionENG: "",
      },
    ],
  },
  {
    categoryID: 6,
    categoryName: "Garnituri / Side Dishes",
    categoryIcon: SideDishIcon,
    products: [
      {
        productID: 38,
        nameRO: "Cartofi Prajiti",
        nameENG: "French Fries",
        quantity: "15 gr",
        price: 9,
        descriptionRO: "",
        descriptionENG: "",
      },
      {
        productID: 39,
        nameRO: "Piure de cartofi",
        nameENG: "Mashed potatoes",
        alergens: "[2]",
        quantity: "150 gr",
        price: 8,
        descriptionRO: "",
        descriptionENG: "",
      },
      {
        productID: 40,
        nameRO: "Legume la gratar",
        nameENG: "Grilled vegetables",
        alergens: "[2]",
        quantity: "150 gr",
        price: 10,
        descriptionRO: "",
        descriptionENG: "",
      },
      {
        productID: 41,
        nameRO: "Iahnie de fasole",
        nameENG: "Baked beans",
        alergens: "[11]",
        quantity: "150 gr",
        price: 10,
        descriptionRO: "",
        descriptionENG: "",
      },
      {
        productID: 42,
        nameRO: "Varza Calita",
        nameENG: "Sauerkrauer",
        quantity: "150 gr",
        price: 10,
        descriptionRO: "",
        descriptionENG: "",
      },
    ],
  },
  {
    categoryID: 7,
    categoryName: "Salate / Salads",
    categoryIcon: SaladIcon,
    products: [
      {
        productID: 43,
        nameRO: "Varza fresh",
        nameENG: "fresh cabbage",
        quantity: "150 gr",
        price: 9,
        descriptionRO: "",
        descriptionENG: "",
      },
      {
        productID: 44,
        nameRO: "Varza murata",
        nameENG: "Pickled cabbage",
        alergens: "[14]",
        quantity: "150 gr",
        price: 9,
        descriptionRO: "",
        descriptionENG: "",
      },
      {
        productID: 45,
        nameRO: "Muraturi asortate",
        nameENG: "Pickled mix",
        alergens: "[14]",
        quantity: "150 gr",
        price: 9,
        descriptionRO: "",
        descriptionENG: "",
      },
      {
        productID: 46,
        nameRO: "Salata de ceapa",
        nameENG: "Onion salad",
        quantity: "70 gr",
        price: 4,
        descriptionRO: "",
        descriptionENG: "",
      },
    ],
  },
  {
    categoryID: 8,
    categoryName: "Paste / Pasta",
    categoryIcon: PastaIcon,
    products: [
      {
        productID: 47,
        nameRO: "Penne quattro formaggi",
        nameENG: "Pene quattro formaggi",
        alergens: "[2, 9]",
        quantity: "350 gr",
        price: 34,
        descriptionRO:
          "Gorgonzola, parmezan, mozzarella, svaiter, pene, smantana, unt",
        descriptionENG:
          "Gorgonzola, parmesan, mozzarella, Schweitzer cheese, pene, sour cream, butter",
      },
      {
        productID: 48,
        nameRO: "Spaghette Bolognese",
        nameENG: "Spaghetti Bolognese",
        alergens: "[2, 9, 11]",
        quantity: "350 gr",
        price: 35,
        descriptionRO: "Sos ragu, spaghete",
        descriptionENG: "Ragu sauce, spaghetti",
      },
    ],
  },
  {
    categoryID: 9,
    categoryName: "Desert",
    categoryIcon: DessertIcon,
    products: [
      {
        productID: 49,
        nameRO: "Tort de ciocolata Bueno",
        nameENG: "Bueno chocolate cake",
        quantity: "120 gr",
        price: 14,
        descriptionRO: "",
        descriptionENG: "",
      },
      {
        productID: 50,
        nameRO: "Lava Cake",
        alergens: "[1, 2]",
        nameENG: "Lava Cake",
        quantity: "125 gr",
        price: 14,
        descriptionRO: "",
        descriptionENG: "",
      },
    ],
  },
  {
    categoryID: 10,
    categoryName: "Pizza",
    categoryIcon: PizzaIcon,
    products: [
      {
        productID: 51,
        nameRO: "Rossignol",
        nameENG: "",
        alergens: "[2, 9]",
        quantity: "575 gr",
        price: 36,
        descriptionRO:
          "Sos de rosii, mozzarella, sunca, ciuperci, salam, aredi gras, masline",
        descriptionENG:
          "Tomato sauce, mozzarella, ham, mushrooms, salami, olives",
      },
      {
        productID: 52,
        nameRO: "Special Snow",
        nameENG: "",
        alergens: "[2, 9]",
        quantity: "490 gr",
        price: 37,
        descriptionRO:
          "Sos de rosii, mozzarella, emmentaler, cascaval, prosciutto crudo",
        descriptionENG:
          "Tomato sauce, mozzarella, emmental, cheese, prosciutto crudo",
      },
      {
        productID: 53,
        nameRO: "Quattro Formaggi",
        nameENG: "",
        alergens: "[2, 9]",
        quantity: "420 gr",
        price: 35,
        descriptionRO:
          "Sos de rosii, mozzarella, emmentaler, gorgonzola, cascava;",
        descriptionENG:
          "Tomato sauce, mozzarella, emmental, gorgonnzola , cheese",
      },
      {
        productID: 54,
        nameRO: "Margherita",
        nameENG: "",
        alergens: "[2, 9]",
        quantity: "380 gr",
        price: 24,
        descriptionRO: "Sos de rosii, mozzarella",
        descriptionENG: "Tomato sauce, mozzarella",
      },
      {
        productID: 55,
        nameRO: "Funghi",
        nameENG: "",
        alergens: "[2, 9]",
        quantity: "490 gr",
        price: 38,
        descriptionRO: "Sos de rosii, mozzarella, ciuperci",
        descriptionENG: "Tomato sauce, mozzarella, mushrooms",
      },
      {
        productID: 56,
        nameRO: "Prosciutto",
        nameENG: "",
        alergens: "[2, 9]",
        quantity: "490 gr",
        price: 28,
        descriptionRO: "Sos de rosii, mozzarella, sunca",
        descriptionENG: "Tomato sauce, mozzarella, ham",
      },
      {
        productID: 57,
        nameRO: "Prosciutto Funghi",
        nameENG: "",
        alergens: "[2, 9]",
        quantity: "490 gr",
        price: 30,
        descriptionRO: "Sos de rosii, mozzarella, sunca, ciuperci",
        descriptionENG: "Tomato sauce, mozzarella, ham, mushrooms",
      },
      {
        productID: 58,
        nameRO: "Romana",
        nameENG: "",
        alergens: "[2, 9]",
        quantity: "510 gr",
        price: 31,
        descriptionRO: "Sos de rosii, mozzarella, sunca, salam, ciuperci",
        descriptionENG: "Tomatoe sauce, mozzarella, ham, salami, mushrooms",
      },
      {
        productID: 59,
        nameRO: "Capriciosa",
        nameENG: "",
        alergens: "[2, 9]",
        quantity: "510 gr",
        price: 30,
        descriptionRO: "Sos de rosii, mozzarella, ciuperci, anghinare, sunca",
        descriptionENG:
          "Tomatoe sauce, mozzarella, mushrooms, artichoke hearts, ham",
      },
      {
        productID: 60,
        nameRO: "Quattro Stagioni",
        nameENG: "",
        alergens: "[2, 9]",
        quantity: "535 gr",
        price: 31,
        descriptionRO: "Sos de rosii, mozzarella, sunca, anghinare, masline",
        descriptionENG:
          "Tomato sauce, mozzarella, ham, artichoke hearts, olives",
      },
      {
        productID: 61,
        nameRO: "Diavolo",
        nameENG: "",
        alergens: "[2, 9]",
        quantity: "470 gr",
        price: 28,
        descriptionRO: "Sos de rosii, mozzarella, salam picant",
        descriptionENG: "Tomato sauce, mozzarella, spcied salami",
      },
      {
        productID: 62,
        nameRO: "Al Tonno",
        nameENG: "",
        alergens: "[2, 3, 9]",
        quantity: "490 gr",
        price: 31,
        descriptionRO: "Sos de rosii, mozzarella, ton, ceapa",
        descriptionENG: "Tomato sauce, mozzarella, tuna, onion",
      },
      {
        productID: 63,
        nameRO: "Hawai",
        nameENG: "",
        alergens: "[2, 9]",
        quantity: "375 gr",
        price: 27,
        descriptionRO: "Sos de rosii, mozzarella, ananas",
        descriptionENG: "Tomato sauce, mozzarella, pineapple",
      },
      {
        productID: 64,
        nameRO: "Dracula",
        nameENG: "",
        alergens: "[2, 9]",
        quantity: "470 gr",
        price: 30,
        descriptionRO:
          "Sos de rosii, mozzarella, bacon, ceapa, usturoi, ardei iute",
        descriptionENG:
          "Tomato sauce, mozzarella, bacon, onion, garlic, chili pepper",
      },
      {
        productID: 65,
        nameRO: "Mexicana",
        nameENG: "",
        alergens: "[2, 9]",
        quantity: "480 gr",
        price: 29,
        descriptionRO: "Sos de rosii, mozzarella, carnati, ardei iute",
        descriptionENG: "Tomato sauce, mozzarella, sausages, chili pepper",
      },
      {
        productID: 66,
        nameRO: "Vegetariana",
        nameENG: "",
        alergens: "[2, 9]",
        quantity: "470 gr",
        price: 27,
        descriptionRO:
          "Sos de rosii, mozzarella, ciuperci, porumb, ardei gras, rosi, masline",
        descriptionENG:
          "Tomato sauce, mozzarella, mushrroms, corn, bell pepper, tomatoes, olives",
      },
      {
        productID: 67,
        nameRO: "Quattro Carni",
        nameENG: "",
        alergens: "[2, 9]",
        quantity: "470 gr",
        price: 34,
        descriptionRO: "Sos de rosii, mozzarella, sunca, bacon, carnati, salam",
        descriptionENG:
          "Tomato sauce, mozzarella, ham, bacon, sausages, salami",
      },
      {
        productID: 68,
        nameRO: "Focaccia",
        nameENG: "",
        alergens: "[9]",
        quantity: "420 gr",
        price: 13,
        descriptionRO: "",
        descriptionENG: "",
      },
      {
        productID: 69,
        nameRO: "Sos dulce / Sos picant",
        nameENG: "Sweet sauce / Spicy sauce",
        quantity: "50 gr",
        price: 3,
        descriptionRO: "",
        descriptionENG: "",
      },
    ],
  },
];

export default RESTAURANT_DATA;
